/** Cities and states for Nigeria corridor parsing (longer keys matched first). */
export const NIGERIA_PLACE_KEYS: string[] = [
  "port harcourt",
  "benin city",
  "cross river",
  "akwa ibom",
  "fct abuja",
  "abuja fct",
  "lagos state",
  "rivers state",
  "enugu state",
  "kano state",
  "ogun state",
  "oyo state",
  "delta state",
  "edo state",
  "imo state",
  "kaduna state",
  "plateau state",
  "niger state",
  "borno state",
  "bayelsa state",
  "abia state",
  "anambra state",
  "kwara state",
  "nasarawa state",
  "zamfara state",
  "sokoto state",
  "taraba state",
  "yobe state",
  "kebbi state",
  "katsina state",
  "jigawa state",
  "gombe state",
  "bauchi state",
  "benue state",
  "ebonyi state",
  "ekiti state",
  "ondo state",
  "osun state",
  "lagos",
  "abuja",
  "ibadan",
  "kano",
  "enugu",
  "benin",
  "owerri",
  "calabar",
  "uyo",
  "warri",
  "aba",
  "jos",
  "ilorin",
  "maiduguri",
  "zaria",
  "akure",
  "abeokuta",
  "onitsha",
  "nigeria",
];

export const NIGERIA_PLACES: Record<string, string> = {
  "port harcourt": "Port Harcourt",
  "benin city": "Benin City",
  benin: "Benin City",
  lagos: "Lagos",
  "lagos state": "Lagos",
  abuja: "Abuja",
  "fct abuja": "Abuja",
  "abuja fct": "Abuja",
  ibadan: "Ibadan",
  kano: "Kano",
  "kano state": "Kano",
  enugu: "Enugu",
  "enugu state": "Enugu",
  owerri: "Owerri",
  "imo state": "Imo",
  calabar: "Calabar",
  "cross river": "Cross River",
  uyo: "Uyo",
  "akwa ibom": "Akwa Ibom",
  warri: "Warri",
  "delta state": "Delta",
  aba: "Aba",
  "abia state": "Abia",
  jos: "Jos",
  "plateau state": "Plateau",
  ilorin: "Ilorin",
  "kwara state": "Kwara",
  maiduguri: "Maiduguri",
  "borno state": "Borno",
  zaria: "Zaria",
  "kaduna state": "Kaduna",
  akure: "Akure",
  "ondo state": "Ondo",
  abeokuta: "Abeokuta",
  "ogun state": "Ogun",
  onitsha: "Onitsha",
  "anambra state": "Anambra",
  "rivers state": "Rivers",
  "oyo state": "Oyo",
  "edo state": "Edo",
  "niger state": "Niger",
  "nasarawa state": "Nasarawa",
  "zamfara state": "Zamfara",
  sokoto: "Sokoto",
  "sokoto state": "Sokoto",
  "taraba state": "Taraba",
  "yobe state": "Yobe",
  "kebbi state": "Kebbi",
  "katsina state": "Katsina",
  "jigawa state": "Jigawa",
  "gombe state": "Gombe",
  "bauchi state": "Bauchi",
  "benue state": "Benue",
  "ebonyi state": "Ebonyi",
  "ekiti state": "Ekiti",
  "osun state": "Osun",
  "bayelsa state": "Bayelsa",
  nigeria: "Nigeria",
};

export function resolveNigeriaPlace(raw: string): string | undefined {
  const key = raw.trim().toLowerCase();
  return NIGERIA_PLACES[key];
}
